name: Continuous Delivery

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18.13.x
      - name: npm install
        run: npm ci
      - name: npm test
        run: npm test -ws --if-present
      - name: import secrets
        id: import-secrets
        uses: LanceMcCarthy/akeyless-action@v3
        with:
          access-id: ${{ secrets.GH_AKEYLESS_ACCESS_ID }}
          static-secrets: |
            {
              "/WebComponents/prod/tokens/GH_TOKEN": "GH_TOKEN",
              "/WebComponents/prod/tokens/PROGRESS_NPM_REGISTRY_TOKEN": "NPM_TOKEN"
            }
          export-secrets-to-environment: false
      - name: semantic release
        run: npm run semantic-release
        env:
          NPM_TOKEN: ${{ steps.import-secrets.outputs.NPM_TOKEN }}
          GH_TOKEN: ${{ steps.import-secrets.outputs.GH_TOKEN }}
