name: Continuous Integration

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ^18.17
      - name: npm install
        run: npm ci
      - name: npm test
        run: npm test -ws --if-present
      - name: npm pack
        run: npm pack --ws
      - name: upload artefacts
        uses: actions/upload-artifact@v3
        with:
          name: artefacts
          path: |
            **/*.tgz